---
version: '3.7'
services:
  mta:
    image: mailad/mta
    build: .
    domainname: mailad.cu
    hostname: mta
    environment:
      # POSTFIX_MAX_MESSAGESIZE: 2264924 # bytes ~1024 * 1024 * MB * 1.08
      # POSTFIX_REALY: 
      # POSTFIX_ALWAYS_BCC: piler@mailad.cu
      # POSTFIX_NATIONAL: cu
      # POSTFIX_EVERYONE: todos@mailad.cu # if not explicit: disabled
      # POSTFIX_SPF_ENABLE: True
      # POSTFIX_DNSBL: True
      POSTFIX_DOMAIN: mailad.cu
      POSTFIX_MAILADMIN: pavel@mailad.cu
      POSTFIX_LDAP_URI: "ldap://dc:389"
      POSTFIX_LDAP_SEARCH_BASE: "OU=MAILAD,DC=mailad,DC=cu"
      POSTFIX_LDAP_BINDUSER: "CN=linux,CN=Users,DC=mailad,DC=cu"
      POSTFIX_LDAP_BINDUSER_PASSWD: "P4ssw0rd."
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "10025:10025"
    volumes:
      - ../ldata/vmail:/home/vmail
      - ../ldata/certs:/certs
